# Generated by Django 5.2.7 on 2025-11-14 06:05

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_encryptedfile_delete_securefile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to=api.models.get_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('blockchain_hash', models.CharField(blank=True, help_text='Cryptographic hash for blockchain verification.', max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiving_user', models.ForeignKey(blank=True, help_text='User who will receive this file (for shared files)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_files', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EncryptedFile',
        ),
    ]
